package app.vetra.ai.provider.gemini;

import java.math.BigDecimal;
import java.util.List;

/**
 * Internal DTO mapping structured JSON generated by Gemini Vision.
 *
 * @param condition suspected clinical condition
 * @param confidence confidence score between 0.0 and 1.0
 * @param observations list of observed symptoms
 * @param recommendations list of recommended immediate actions
 * @param requiresVeterinarianReview boolean indicator
 */
public record GeminiDiagnosticPayload(
    String condition,
    BigDecimal confidence,
    List<String> observations,
    List<String> recommendations,
    Boolean requiresVeterinarianReview) {}
